name: Deploy FastAPI RAG to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 3. Set up gcloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 4. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 5. Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      # 6. Install Python dependencies (torch included in Docker image if needed)
      - name: Install dependencies
        run: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

      # 7. Deploy directly from source to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-rag-service \
            --source . \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=europe-west1 \
            --allow-unauthenticated \
            --port=8080
            --timeout=10m
