name: Deploy FastAPI RAG to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy FastAPI App
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

   
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

     
      - name: Create .env file from secrets
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "VECTOR_SIZE=${{ secrets.VECTOR_SIZE }}" >> .env

      
      - name: Push prebuilt Docker image
        run: |
          docker tag fastapi-rag:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-rag:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-rag:latest


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-rag-service \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi-rag:latest \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8000 \
            --timeout 15m
