name: Deploy FastAPI App to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Step 3: Setup Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Step 4: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-service \
            --source . \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --region=europe-west1 \
            --allow-unauthenticated \
            --port=8080 \
            --update-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},\
SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL }},\
SUPABASE_URL=${{ secrets.SUPABASE_URL }},\
SUPABASE_KEY=${{ secrets.SUPABASE_KEY }},\
VECTOR_SIZE=${{ secrets.VECTOR_SIZE }}
